version: '3.8'

services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - escrow-database:/var/lib/mysql
    expose:
      - '40000'
    ports:
      - '40000:3306'
    networks:
      - local
  cache:
    image: 'bitnami/redis:latest'
    restart: always
    environment:
      ALLOW_EMPTY_PASSWORD: no
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    volumes:
      - escrow-cache:/var/lib/redis
    expose:
      - ${REDIS_PORT}
    ports:
      - ${REDIS_PORT}:6379
    networks:
      local:

volumes:
  escrow-database:
    driver: local
  escrow-cache:
    driver: local

networks:
  local:
    driver: bridge

