version: '3.8'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - escrow-database:/var/lib/postgresql/data
    expose:
      - "${POSTGRES_PORT}"
    ports:
      - "${POSTGRES_PORT}:5432"
    networks:
      - local
  cache:
    image: 'bitnami/redis:latest'
    restart: always
    environment:
      ALLOW_EMPTY_PASSWORD: no
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    volumes:
      - escrow-cache:/var/lib/redis
    expose:
      - ${REDIS_PORT}
    ports:
      - ${REDIS_PORT}:6379
    networks:
      local:

volumes:
  escrow-database:
    driver: local
  escrow-cache:
    driver: local

networks:
  local:
    driver: bridge

